#-----------------------------------------------------------------------------
#
#  Configuration for continuous integration service at appveyor.com
#
#-----------------------------------------------------------------------------

# branches to build
#branches:
#  # whitelist
#  only:
#    - master

# Operating system (build VM template)
os: Visual Studio 2015

environment:
  nodejs_version: "0.10.33"

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: c:\projects\node-osmium

platform: x64

build_script:
  - scripts\build-appveyor.bat

test: off
deploy: off
